apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-pr-to-existing-project
  title: Create PR to existing project
  description: Create PR to existing project

spec:
  owner: info@roadie.io
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
        description:
          title: Description
          type: string
          description: Help others understand what this project is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: '${{ parameters.component_id }}'
          description: '${{ parameters.description }}'
          destination: '${{ parseRepoUrl parameters.repoUrl }}'
          owner: '${{ parameters.owner }}'

    - action: fs:rename
      id: rename-files
      name: Rename files
      input:
        files:
          - from: .github/workflows/pull-request.yaml
            to: .github/workflows/pull-request.yaml


    - id: log-message
      name: Log Message
      action: debug:log
      input:
        listWorkspace: true

    - action: publish:github:pull-request
      id: create-pull-request
      name: Create a pull request
      input:
        repoUrl: 'github.com?repo=software-templates&owner=Xantier'
        branchName: ticketNumber-123
        title: 'Make some changes to the files'
        description: 'This pull request makes changes to the files in the reponame repository in the AcmeInc organization'
        #targetPath: ./subdirectory

  output:
    remoteUrl: '${{ steps.publish.output.remoteUrl }}'
