apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-tenant
  title: Create Tenant
  description: Send an API call to the tenant manager to create a tenant.

spec:
  owner: user:dtuite
  type: none
  parameters:
    - title: Provide some simple information
      required:
        - tenant_name
        - tenant_email_domain
        - admin_email
        - tenant_environment
      properties:
        tenant_name:
          title: Name
          type: string
          description: No special chars, numbers as the first char, or dashes as the first or last char. 
          ui:autofocus: true
        tenant_email_domain:
          title: Email domain
          type: string
          description: The email domain of users who will be allowed to access the tenant.
        admin_email:
          title: Admin email
          type: string
          description: The email of the person who will drive the evaluation.
        tenant_environment:
          title: Environment
          type: string
          default: dev
          enum: ['dev', 'prod']
            
  steps:
    - id: createTenant
      name: Create tenant
      action: http:backstage:request
      input:
        method: 'POST'
        path: /api/proxy/dev-tenant-manager/api/tenant
        headers:
          # This is specified here rather than in the proxy in order to ensure that
          # http:backstage:request treats the body as JSON.
          content-type: 'application/json'
        body:
          adminEmail: ${{ parameters.admin_email }}
          tenantName: ${{ parameters.tenant_name }}
          tenantEmailDomain: ${{ parameters.tenant_email_domain }}
          tenantEnvironment: dev
          skipFailures: true

  output:
    resp: ${{ steps.callTenantManager.output.body }}
